CXX = gcc
CXXFLAGS = `llvm-config --cxxflags`
LDFLAGS = `llvm-config --ldflags`
LIBS = -lstdc++ `llvm-config --system-libs --libs all`
SRC = assembly.cpp core.cpp initfini.cpp module.cpp value.cpp \
	  executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp \
	  linker.cpp
OUTPUT = libllvmlite.so

all: $(SRC)
	$(CXX) -shared $(CXXFLAGS) $(SRC) -o $(OUTPUT) $(LDFLAGS) $(LIBS)


clean:
	rm -rf test
