package:
  name: llvmlite
  # GIT_DESCRIBE_TAG may not be set
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    # We cannot do this on macOS as the llvm-config from the
    # toolchain conflicts with the same from llvmdev, the
    # build.sh deals with it!
    - {{ compiler('c') }}    # [not osx]
    - {{ compiler('cxx') }}  # [not osx]
    # The DLL build uses cmake on Windows
    - cmake          # [win]
  host:
    - python
    # On channel https://anaconda.org/numba/
    - llvmdev 6.0*
    - vs2015_runtime # [win]
    - enum34         # [py27]
    # llvmdev is built with libz compression support
    - zlib           # [unix]
  run:
    - python
    - enum34         # [py27]
    - vs2015_runtime # [win]
    # osx has dynamically linked libstdc++
    - libcxx >=4.0.1 # [osx]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
