package:
  name: llvmlite
  # GIT_DESCRIBE_TAG may not be set
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    # On channel https://anaconda.org/numba/
    - llvmdev 3.9*
    # Those are copied into the llvmlite packages
    - vs2013_runtime [win]
    # The DLL build uses cmake on Windows
    - cmake          [win]
    - enum34         [py27]
  run:
    - python
    - enum34         [py27]

test:
  imports:
    - llvmlite
    - llvmlite.binding

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
