package:
  name: llvmlite
  # GIT_DESCRIBE_TAG may not be set
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../..
  #git_url: https://github.com/numba/llvmlite.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
      # On channel https://binstar.org/numba/
    - llvmdev 3.6*
    #- cmake          [win]
    - enum34         [py26 or py27 or py33]
  run:
    - python
    - enum34         [py26 or py27 or py33]

test:
  requires:
    - argparse       [py26]
    - unittest2      [py26]
  imports:
    - llvmlite
    - llvmlite.binding

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
