{% set VERSION_SUFFIX = "" %} # debug version suffix, appended to the version

package:
  name: llvmlite
  # GIT_DESCRIBE_TAG may not be set
  version: {{ "%s%s" % (environ.get('GIT_DESCRIBE_TAG', '').lstrip('v'), VERSION_SUFFIX) }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    # We cannot do this on macOS as the llvm-config from the
    # toolchain conflicts with the same from llvmdev, the
    # build.sh deals with it!
    - {{ compiler('c') }}    # [not (osx or armv6l or armv7l)]
    - {{ compiler('cxx') }}  # [not (osx or armv6l or armv7l)]
    # The DLL build uses cmake on Windows
    #- cmake          # [win]
    - make           # [unix and not (armv6l or armv7l or aarch64)]
  host:
    - python
    # On channel https://anaconda.org/numba/
    # Build using LLVM (llvmdev) 10.0.1-1 on most platforms
    - llvmdev 10.0.1 *1 # [not aarch64 and not win]
    - llvmdev 10.0.1 1 # [win]
    # Build using LLVM (llvmdev) 9.0.* on aarch64
    - llvmdev 9.0.* # [aarch64]
    # - vs2015_runtime # [win]
    # llvmdev is built with libz compression support
    - zlib           # [unix and not (armv6l or armv7l or aarch64)]
  run:
    - python >=3.6
    - vs2015_runtime # [win]
    # osx has dynamically linked libstdc++
    - libcxx >=4.0.1 # [osx]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
