parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      py39:
        PYTHON: '3.9'
        CONDA_ENV: cienv
      py310:
        PYTHON: '3.10'
        CONDA_ENV: cienv
      py311:
        PYTHON: '3.11'
        CONDA_ENV: cienv
      py312:
        PYTHON: '3.12'
        CONDA_ENV: cienv

      llvm15:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        LLVM: '15'

  steps:

    - powershell: |
        $wc = New-Object net.webclient
        $wc.Downloadfile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe", "Miniconda3-latest-Windows-x86_64.exe")
        Start-Process "Miniconda3-latest-Windows-x86_64.exe" "/S /D=C:\Miniconda3" -Wait
      displayName: 'Install miniconda'

    - script: |
        call C:\Miniconda3\Scripts\activate.bat
        call buildscripts\\incremental\\setup_conda_environment.cmd
      displayName: 'Before Install'

    - script: |
        call C:\Miniconda3\Scripts\activate.bat
        call buildscripts\\incremental\\build.cmd
      displayName: 'Build'

    - script: |
        call C:\Miniconda3\Scripts\activate.bat
        call buildscripts\\incremental\\test.cmd
      displayName: 'Test'
