parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      py310:
        PYTHON: '3.10'
        CONDA_ENV: cienv
      py311:
        PYTHON: '3.11'
        CONDA_ENV: cienv
      py312:
        PYTHON: '3.12'
        CONDA_ENV: cienv
      py313:
        PYTHON: '3.13'
        CONDA_ENV: cienv

      opaque_pointers:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        OPAQUE_POINTERS: yes

  steps:

    - powershell: |
        $wc = New-Object net.webclient
        # Add User-Agent header to prevent 403 Forbidden error when downloading Miniconda
        # Some servers block requests without proper User-Agent headers
        $wc.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36")
        $wc.Downloadfile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe", "Miniconda3-latest-Windows-x86_64.exe")
        Start-Process "Miniconda3-latest-Windows-x86_64.exe" "/S /D=C:\Miniconda3" -Wait
      displayName: 'Install miniconda'

    - script: |
        call C:\Miniconda3\Scripts\activate.bat
        call buildscripts\\incremental\\setup_conda_environment.cmd
      displayName: 'Before Install'

    - script: |
        call C:\Miniconda3\Scripts\activate.bat
        call buildscripts\\incremental\\build.cmd
      displayName: 'Build'

    - script: |
        call C:\Miniconda3\Scripts\activate.bat
        call buildscripts\\incremental\\test.cmd
      displayName: 'Test'
