blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://numba.discourse.group/c/llvmlite
    about: "If you have a general question (not a bug report or feature request) then please ask in the llvmlite section of Numba's discourse instance."
  - name: Quick Question/Just want to say Hi!
    url: https://gitter.im/numba/llvmlite
    about: "If you have a quick question or want chat to users/developers in real time then please use gitter.im/numba/llvmlite"
  - name: Discuss an involved feature
    url: https://numba.discourse.group/c/llvmlite
    about: "If you would like to suggest a more involved feature like *Can a new pass be added to do X* then please start a discussion in the llvmlite section of Numba's discourse instance."
