package:
  name: llvmdev
  version: "3.6.2"

source:
  fn: llvm-3.6.2.src.tar.xz
  url: http://llvm.org/releases/3.6.2/llvm-3.6.2.src.tar.xz
  sha1: 7a00257eb2bc9431e4c77c3a36b033072c54bc7e
  patches:
    # From http://reviews.llvm.org/D6052
    - ../llvm-elf-relocation.patch

build:
  number: 1

requirements:
  build:
    - system           [linux and not armv7l]
  run:
    - system           [linux and not armv7l]

test:
  commands:
    - llvm-config --libs   [linux]
    - llc -version         [linux]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.6.0/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
