
{% set shortversion = "3.8" %}
{% set version = "3.8.1" %}
{% set sha256 = "6e82ce4adb54ff3afc18053d6981b6aed1406751b8742582ed50f04b5ab475f9" %}

package:
  name: llvmdev
  version: "3.8.1"

source:
  fn: llvm-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  url: http://llvm.org/releases/3.8.1/llvm-3.8.1.src.tar.xz
  patches:
    # https://llvm.org/bugs/show_bug.cgi?id=15356
    - ../llvm-elf-relocation.patch
    # https://llvm.org/bugs/show_bug.cgi?id=25788
    - ../llvm-parse-fp-constants.patch
    # https://llvm.org/bugs/show_bug.cgi?id=25565
    - ../llvm-build-race-condition.patch
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - ../llvm-lto-static.patch   # [win]

build:
  number: 7

requirements:
  build:
    - cmake
    # Needed to unpack the source tarball
    - m2w64-xz         # [py27 and win]
    # Needed to build LLVM
    - python
    - system           # [linux and not armv7l]
  run:
    - system           # [linux and not armv7l]

test:
  commands:
    - llvm-config --libs   # [not win]
    - llc -version

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1          # [win]
    - if not exist %LIBRARY_LIB%\\LLVMSupport.lib exit 1       # [win]

    - test -f $PREFIX/include/llvm/Pass.h                      # [unix]
    - test -f $PREFIX/lib/libLLVMSupport.a                     # [unix]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM
