{% set shortversion = "7.0" %}
{% set version = "7.0.0" %}
{% set version_suffix = "_perf_tool" %}
{% set sha256_llvm = "8bc1f844e6cbde1b652c19c1edebc1864456fd9c78b8c1bea038e51b363fe222" %}
{% set sha256_lld = "fbcf47c5e543f4cdac6bb9bbbc6327ff24217cd7eafc5571549ad6d237287f9c" %}
{% set build_number = "0" %}

package:
  name: llvmdev
  version: {{ "%s%s" % (version, version_suffix) }}

source:
  - url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
    fn: llvm-{{ version }}.src.tar.xz
    sha256: {{ sha256_llvm }}
    patches:
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - ../llvm-lto-static.patch   # [win]
    - ../partial-testing.patch
    # Intel SVML optimizations
    # The second part of this patch was published as:
    # https://reviews.llvm.org/D53035
    # (the first, as mentioned in the patch itself, was:
    # https://reviews.llvm.org/D47188)
    - ../D47188-svml-VF.patch
    # undefined behavior bug due to Twine usage
    - ../twine_cfg_undefined_behavior.patch
    # Patches for X86 common symbols over-allocation and testing thereof, see
    # https://reviews.llvm.org/D50240 and https://reviews.llvm.org/rL340788
    # for details:
    - ../0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch
    - ../0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch
    # Patch based on: https://reviews.llvm.org/D47343
    # to allow linux perf to work with MCJIT
    - ../0001-perf_tools.patch # [linux]

  - url: http://releases.llvm.org/{{ version }}/lld-{{ version }}.src.tar.xz
    fn: lld-{{ version }}.src.tar.xz
    sha256: {{ sha256_lld }}
    folder: tools/lld

build:
  number: {{ build_number }}
  script_env:
    - PY_VCRUNTIME_REDIST
  ignore_run_exports:
    # Is static-linked
    - xar

requirements:
  build:
    # We cannot do this on macOS or windows
    # OSX already has llvm so has to be handled
    # at build.sh time
    # Windows needs to build using vs2015_runtime
    # irrespective of python version
    - {{ compiler('c') }} # [unix and not (armv6l or armv7l or aarch64)]
    - {{ compiler('cxx') }} # [unix and not (armv6l or armv7l or aarch64)]
    - cmake # [not (armv6l or armv7l)]
    # Needed to unpack the source tarball
    - m2w64-xz  # [py27 and win]
    # ninja not currently used, bld.bat needs an update
    - ninja  # [win]
    # Needed to build LLVM
    - python >=3
    # need vs2015_runtime to build, do not want it at run time
    # as extensions for py27 need vs2008
    - vs2015_runtime # [win]
    - make # [unix and not (armv6l or armv7l or aarch64)]
  host:
    # needed for llc at runtime
    - zlib # [not win]
    - xar # [osx]
    # llvm-lit testing needs *a* python
    - python # [not (armv6l or armv7l or aarch64 or win)]

test:
  requires:
    - python
  files:
    - cfg_test.ll
    - numba-3016.ll
    - test_cfg_dot.py
  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\LLVMSupport.lib exit 1     # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMSupport.a                   # [unix]

    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]
    # Test for ../twine_cfg_undefined_behavior.patch
    - $PREFIX/bin/opt -dot-cfg cfg_test.ll                   # [not win]
    - python test_cfg_dot.py                                 # [not win]

    # LLD tests
    - ld.lld --version                                       # [unix]
    - lld-link /?                                            # [win]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM
