package:
  name: llvmdev
  version: "3.8.1"

source:
  fn: llvm-3.8.1.src.tar.xz
  url: http://llvm.org/releases/3.8.1/llvm-3.8.1.src.tar.xz
  sha1: e0c48c4c182424b99999367d688cd8ce7876827b
  patches:
    # https://llvm.org/bugs/show_bug.cgi?id=15356
    - ../llvm-elf-relocation.patch
    # https://llvm.org/bugs/show_bug.cgi?id=25788
    - ../llvm-parse-fp-constants.patch
    # https://llvm.org/bugs/show_bug.cgi?id=25565
    - ../llvm-build-race-condition.patch
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - ../llvm-lto-static.patch   [win]

build:
  number: 6

requirements:
  build:
    - cmake
    # Needed to unpack the source tarball
    - m2-xz            [py27 and win32]
    - m2w64-xz         [py27 and win64]
    # Needed to build LLVM
    - python
    - system           [linux and not armv7l]
  run:
    - system           [linux and not armv7l]

test:
  commands:
    - llvm-config --libs   [not win]
    - llc -version

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/docs/DeveloperPolicy.html#llvm-license)
  summary: Development headers and libraries for LLVM
