package:
  name: llvmdev
  version: "3.7.1"

source:
  fn: llvm-3.7.1.src.tar.xz
  url: http://llvm.org/releases/3.7.1/llvm-3.7.1.src.tar.xz
  sha1: 5dbdcafac105273dcbff94c68837a66c6dd78cef
  patches:
    # From http://reviews.llvm.org/D6052
    - ../llvm-elf-relocation.patch

build:
  number: 2

requirements:
  build:
    - cmake
    - system           [linux and not armv7l]
  run:
    - system           [linux and not armv7l]

test:
  commands:
    - llvm-config --libs   [not win]
    - llc -version         [not win]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.7.0/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
