CI: azure
c_compiler: gcc
c_compiler_version: '11'
cdt_name: cos7
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '11'
docker_image: quay.io/condaforge/linux-anvil-ppc64le
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
libxml2: '2.10'
lua: '5'
numpy: '1.21'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.10'
r_base: '3.5'
target_platform: linux-ppc64le
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
zlib: '1.2'
zstd: '1.5'
