# Conda environment configuration for readthedocs

name: rtdenv
dependencies:
  - python=3.9
  - sphinx
  # https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-fileA
  - docutils==0.16
