name: llvmlite-build

on:
  workflow_dispatch:

jobs:
  build-llvmlite:
    name: Build LLVMLITE Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["cp310-cp310", "cp311-cp311", "cp312-cp312"]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Output Directory
        run: |
          mkdir -p /home/runner/work/llvmlite/llvmlite/docker_output
          chmod 777 /home/runner/work/llvmlite/llvmlite/docker_output

      - name: Build LLVMLITE
        run: |
          cd buildscripts/manylinux
          chmod +x ./docker_run_x64.sh
          ./docker_run_x64.sh build_llvmlite.sh "${{ matrix.python-version }}"

      - name: Upload LLVMLITE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvmlite-${{ matrix.python-version }}
          path: /home/runner/work/llvmlite/llvmlite/docker_output/dist_x86_64_${{ matrix.python-version }}/wheelhouse/*.whl
          retention-days: 7
          if-no-files-found: error
