name: llvmlite-build

on:
  workflow_dispatch:

jobs:
  build-llvmlite:
    name: Build LLVMLITE Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false
    outputs:
      matrix: ${{ toJSON(matrix) }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Miniconda
        run: |
          bash buildscripts/incremental/install_miniconda.sh
      
      - name: Add Conda to PATH
        run: |
          echo "$HOME/miniconda3/bin" >> $GITHUB_PATH
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda init bash
      
      - name: Create Build Environment
        run: |
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda create -n build_env \
            python=${{ matrix.python-version }} \
            conda-build \
            conda-verify \
            -y
          
          conda activate build_env
          conda config --set always_yes yes --set changeps1 no

      - name: Build LLVMLITE
        run: |
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda activate build_env
          # Set version info for conda build
          COMMIT_SHA=$(git rev-parse --short HEAD)
          export GIT_DESCRIBE_TAG="v0.dev0+${COMMIT_SHA}"
          export GIT_DESCRIBE_NUMBER=0
          conda build conda-recipes/llvmlite \
            --python ${{ matrix.python-version }} \
            --output-folder ./conda_output

      - name: Upload LLVMLITE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvmlite-py${{ matrix.python-version }}
          path: ./conda_output/linux-64/*.tar.bz2
          retention-days: 7
          if-no-files-found: error

  test-llvmlite:
    needs: build-llvmlite
    name: Test LLVMLITE Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.build-llvmlite.outputs.matrix).python-version }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install Miniconda
        run: |
          bash buildscripts/incremental/install_miniconda.sh
      
      - name: Add Conda to PATH
        run: |
          echo "$HOME/miniconda3/bin" >> $GITHUB_PATH
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda init bash

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: llvmlite-py${{ matrix.python-version }}
          path: ./conda_pkg

      - name: Create Test Environment
        run: |
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda create -n test_env \
            python=${{ matrix.python-version }} \
            -y
          
          conda activate test_env
          conda install -c ./conda_pkg llvmlite -y

      - name: Run Tests
        run: |
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda activate test_env
          python -m llvmlite.tests
