name: llvmlite-build

on:
  workflow_dispatch:

jobs:
  build-llvmlite:
    name: build_linux_64_py${{ matrix.python-version }}_npy1.11
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    outputs:
      matrix: ${{ toJSON(matrix) }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Miniconda
        run: |
          bash buildscripts/incremental/install_miniconda.sh
      
      - name: Add Conda to PATH
        run: |
          echo "$HOME/miniconda3/bin" >> $GITHUB_PATH
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda init bash
      
      - name: Create Build Environment
        run: |
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda create -n build_env \
            python=${{ matrix.python-version }} \
            setuptools \
            wheel \
            -y
          conda activate build_env
          conda install -y numba/label/ci::llvmdev --no-deps

      - name: build_linux_64_py${{ matrix.python-version }}_npy1.11
        run: |
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda activate build_env
          # Build with static linking like manylinux
          export LLVMLITE_CXX_STATIC_LINK=1
          # Set LLVM_CONFIG to point to the correct llvm-config
          export LLVM_CONFIG="$CONDA_PREFIX/bin/llvm-config"
          # Ensure shared library is built
          export LLVMLITE_SHARED=1
          
          # Clean up
          python setup.py clean
          # Build wheel
          python setup.py bdist_wheel

      - name: test_linux_64_py${{ matrix.python-version }}_npyNone
        run: |
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda activate build_env
          python -m pip install dist/*.whl
          python -m llvmlite.tests

      - name: upload_linux_64_py${{ matrix.python-version }}
        uses: actions/upload-artifact@v4
        with:
          name: llvmlite-py${{ matrix.python-version }}
          path: dist/*.whl
          retention-days: 7
          if-no-files-found: error

