name: Test Manylinux Builds

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        type: choice
        required: true
        default: 'all'
        options:
          - all
          - select
      python_310:
        description: 'Build Python 3.10'
        type: boolean
        required: false
        default: false
      python_311:
        description: 'Build Python 3.11'
        type: boolean
        required: false
        default: false
      python_312:
        description: 'Build Python 3.12'
        type: boolean
        required: false
        default: false
      python_313:
        description: 'Build Python 3.13'
        type: boolean
        required: false
        default: false

jobs:
  matrix-prep:
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.set-matrix.outputs.python_versions }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ github.event.inputs.build_type }}" == "all" ]]; then
            echo "python_versions=[\"cp310-cp310\",\"cp311-cp311\",\"cp312-cp312\",\"cp313-cp313\"]" >> $GITHUB_OUTPUT
          else
            VERSIONS=""
            ${{ github.event.inputs.python_310 == 'true' }} && VERSIONS="$VERSIONS,\"cp310-cp310\""
            ${{ github.event.inputs.python_311 == 'true' }} && VERSIONS="$VERSIONS,\"cp311-cp311\""
            ${{ github.event.inputs.python_312 == 'true' }} && VERSIONS="$VERSIONS,\"cp312-cp312\""
            ${{ github.event.inputs.python_313 == 'true' }} && VERSIONS="$VERSIONS,\"cp313-cp313\""
            VERSIONS=${VERSIONS#,}
            echo "python_versions=[$VERSIONS]" >> $GITHUB_OUTPUT
          fi

  build-llvmdev-x86:
    needs: matrix-prep
    name: Build LLVMDEV - x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build LLVMDEV
        run: |
          cd buildscripts/manylinux
          chmod +x ./docker_run_x64.sh
          ./docker_run_x64.sh build_llvmdev.sh
      - name: Upload LLVMDEV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvmdev-x86_64
          path: docker_output/*.tar.bz2
          retention-days: 1

  build-llvmdev-arm:
    needs: matrix-prep
    name: Build LLVMDEV - aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Build LLVMDEV
        run: |
          cd buildscripts/manylinux
          chmod +x ./docker_run_aarch64.sh
          ./docker_run_aarch64.sh build_llvmdev.sh
      - name: Upload LLVMDEV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvmdev-aarch64
          path: docker_output/*.tar.bz2
          retention-days: 1

  build-llvmlite-x86:
    needs: [matrix-prep, build-llvmdev-x86]
    name: Build LLVMLITE x86_64 - Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJson(needs.matrix-prep.outputs.python_versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Download LLVMDEV artifacts
        uses: actions/download-artifact@v4
        with:
          name: llvmdev-x86_64
          path: docker_output
      - name: Setup local conda channel
        run: |
          mkdir -p docker_output/linux-64
          mv docker_output/*.tar.bz2 docker_output/linux-64/
          conda index docker_output
      - name: Build LLVMLITE
        run: |
          cd buildscripts/manylinux
          chmod +x ./docker_run_x64.sh
          ./docker_run_x64.sh build_llvmlite.sh ${{ matrix.python_version }}
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvmlite-x86_64-${{ matrix.python_version }}
          path: docker_output/dist_x86_64_${{ matrix.python_version }}/wheelhouse/*.whl
          retention-days: 7

  build-llvmlite-arm:
    needs: [matrix-prep, build-llvmdev-arm]
    name: Build LLVMLITE aarch64 - Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJson(needs.matrix-prep.outputs.python_versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Download LLVMDEV artifacts
        uses: actions/download-artifact@v4
        with:
          name: llvmdev-aarch64
          path: docker_output
      - name: Setup local conda channel
        run: |
          mkdir -p docker_output/linux-aarch64
          mv docker_output/*.tar.bz2 docker_output/linux-aarch64/
          conda index docker_output
      - name: Build LLVMLITE
        run: |
          cd buildscripts/manylinux
          chmod +x ./docker_run_aarch64.sh
          ./docker_run_aarch64.sh build_llvmlite.sh ${{ matrix.python_version }}
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvmlite-aarch64-${{ matrix.python_version }}
          path: docker_output/dist_aarch64_${{ matrix.python_version }}/wheelhouse/*.whl
          retention-days: 7

  collect-results:
    needs: [build-llvmlite-x86, build-llvmlite-arm]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts
      - name: List all built artifacts
        run: |
          echo "Built artifacts:"
          ls -R all-artifacts/